"""Lubricate Magnetic Compensation — public API."""

from lmc.calibration import CalibrationResult, calibrate
from lmc.columns import (
    COL_ALT,
    COL_BTOTAL,
    COL_BX,
    COL_BY,
    COL_BZ,
    COL_COS_X,
    COL_COS_X2,
    COL_COS_X_DCOS_X,
    COL_COS_X_DCOS_Y,
    COL_COS_X_DCOS_Z,
    COL_COS_XY,
    COL_COS_XZ,
    COL_COS_Y,
    COL_COS_Y2,
    COL_COS_Y_DCOS_X,
    COL_COS_Y_DCOS_Y,
    COL_COS_Y_DCOS_Z,
    COL_COS_YZ,
    COL_COS_Z,
    COL_COS_Z2,
    COL_COS_Z_DCOS_X,
    COL_COS_Z_DCOS_Y,
    COL_COS_Z_DCOS_Z,
    COL_DELTA_B,
    COL_HEADING,
    COL_LAT,
    COL_LON,
    COL_PITCH,
    COL_ROLL,
    COL_SEGMENT_LABEL,
    COL_TIME,
    COL_TMI_COMPENSATED,
    REQUIRED_COLUMNS,
)
from lmc.compensation import compensate
from lmc.config import PipelineConfig
from lmc.earth_field import compute_interference
from lmc.features import build_feature_matrix
from lmc.metrics import FomReport, compute_fom_report
from lmc.segmentation import Segment, segment_fom
from lmc.validation import validate_dataframe

__all__ = [
    "CalibrationResult",
    "calibrate",
    "compensate",
    "COL_TMI_COMPENSATED",
    "COL_ALT",
    "COL_BTOTAL",
    "COL_BX",
    "COL_BY",
    "COL_BZ",
    "COL_COS_X",
    "COL_COS_X2",
    "COL_COS_X_DCOS_X",
    "COL_COS_X_DCOS_Y",
    "COL_COS_X_DCOS_Z",
    "COL_COS_XY",
    "COL_COS_XZ",
    "COL_COS_Y",
    "COL_COS_Y2",
    "COL_COS_Y_DCOS_X",
    "COL_COS_Y_DCOS_Y",
    "COL_COS_Y_DCOS_Z",
    "COL_COS_YZ",
    "COL_COS_Z",
    "COL_COS_Z2",
    "COL_COS_Z_DCOS_X",
    "COL_COS_Z_DCOS_Y",
    "COL_COS_Z_DCOS_Z",
    "COL_DELTA_B",
    "COL_HEADING",
    "COL_LAT",
    "COL_LON",
    "COL_PITCH",
    "COL_ROLL",
    "COL_SEGMENT_LABEL",
    "COL_TIME",
    "REQUIRED_COLUMNS",
    "PipelineConfig",
    "Segment",
    "compute_interference",
    "build_feature_matrix",
    "FomReport",
    "compute_fom_report",
    "segment_fom",
    "validate_dataframe",
]
